### ISSUE TITLE
 Error: Neither the resources/app folder nor the resources/app.asar package were found.

### ISSUE THREAD

**Issue by 756613351** [Aluxian/electron-windows-installer#1]
when i gulp create-windows-installer, it happens.it means that my project needs folder 'resource/app'???

**Comment by aluxian** [comment]
I think so. What did you try to package? The `appDirectory` that you give to the plugin should contain a resources folder (directly inside it, afaicr). Do you have it?

**Comment by aluxian** [comment]
Let me know if you still need help.
