### ISSUE TITLE
Creating directory on squirrell install and logs on squirrel events

### ISSUE THREAD

**Issue by drFabio** [Aluxian/electron-windows-installer#12]
I am trying to create a directory on the same level of Update.exe when **--squirrel-install** using fs.mkdirSync but this does not appear to be working.
The path that I am using is:

``` javascript
  path.resolve(path.dirname(process.execPath), "..", "fileResources")
```

Also is there a way to get the console.log on the installation somewhere? I tryied to check SquirrelSetup.log but there is nothing there.

Thanks in advance

**Comment by aluxian** [comment]
> is there a way to get the console.log on the installation somewhere?

There isn't, you have to write the logs to a file yourself.

SquirrelSetup.log contains logs from Squirrel, not from the app.

I'd ask you why what you tried is not working, but without having seen the logs I assume you don't know either.

**Comment by drFabio** [comment]
Yeah I don't know yet I tryied to save on a file on a fixed location but that did not worked also. Will fiddle with it a little and go backto this issue if I solve it or got new info

**Comment by aluxian** [comment]
👍 

Here's how I do it: https://github.com/Aluxian/Whatsie/blob/develop/src/scripts/browser/utils/file-logger.js

**Comment by drFabio** [comment]
I think i was just having a race condition problem launching my app before the setup. Thanks for the snippet as well.
