### ISSUE TITLE
Path too long.

### ISSUE THREAD

**Issue by acostela** [Aluxian/electron-windows-installer#2]
Hi.

I'm trying to use this package and I get the error 

The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

```
at ChildProcess.exithandler (child_process.js:203:12)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:818:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "wininstaller"

I Updated to NPM3 that it's supposed to fix this problem but I'm still getting this error.

**Comment by aluxian** [comment]
Make sure you delete node_modules after you update to npm3. Then, do you still get this? What are the dependencies you're trying to install?

**Comment by acostela** [comment]
Hi. 

I deleted node_modules folder after upgrading to npm3 and I did a new npm install. Everything correct in this step but still getting same error when trying to create the installer. 

My dependencies are the following.

"devDependencies": {
    "angular-mocks": "^1.4.8",
    "bourbon": "^4.2.5",
    "bourbon-neat": "^1.7.2",
    "browser-sync": "^2.11.0",
    "browserify": "^11.1.0",
    "browserify-istanbul": "^0.2.1",
    "browserify-ngannotate": "^2.0.0",
    "browserify-shim": "^3.8.11",
    "bulk-require": "^0.2.1",
    "bulkify": "^1.1.1",
    "canonical-path": "0.0.2",
    "conventional-changelog": "^1.0.1",
    "del": "^2.0.2",
    "dgeni": "^0.4.2",
    "electron-installer-squirrel-windows": "^1.3.0",
    "electron-packager": "^5.1.1",
    "electron-prebuilt": "^0.35.2",
    "electron-windows-installer": "^1.2.5",
    "envify": "^3.4.0",
    "gulp": "^3.9.0",
    "gulp-angular-gettext": "^2.1.0",
    "gulp-angular-templatecache": "^1.8.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-changed": "^1.3.0",
    "gulp-concat": "^2.6.0",
    "gulp-connect": "^2.2.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-jshint": "^2.0.0",
    "gulp-livereload": "^3.8.0",
    "gulp-notify": "^2.2.0",
    "gulp-sass": "^2.0.4",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-streamify": "^1.0.2",
    "gulp-uglify": "^1.5.1",
    "gulp-util": "^3.0.6",
    "highlight.js": "^8.9.1",
    "isparta": "^4.0.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^2.4.0",
    "jshint": "^2.8.0",
    "jshint-stylish": "^2.1.0",
    "karma": "^0.13.15",
    "karma-browserify": "^4.4.2",
    "karma-chrome-launcher": "^0.2.2",
    "karma-jasmine": "^0.3.6",
    "karma-ng-html2js-preprocessor": "^0.2.0",
    "protractor": "^3.0.0",
    "run-sequence": "^1.1.5",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.4.0"
  },
  "dependencies": {
    "angular": "1.4.4",
    "angular-gettext": "^2.1.2",
    "angular-hammer": "^2.1.10",
    "angular-ui-router": "^0.2.15",
    "jquery": "^2.2.0",
    "lodash": "^3.10.1",
    "moment": "^2.10.6"
  }

**Comment by acostela** [comment]
I close this issue due to it was an error with an internal file that wasn't correctly erased. Thank you for your attention.
