### ISSUE TITLE
The specified path, file name, or both are too long

### ISSUE THREAD

**Issue by balakrishnan4587** [Aluxian/electron-windows-installer#4]
when i running "gulp create-windows-installer" command i am getting this error.. i am uisng windows 7 & 32bit. thanks.

**Comment by aluxian** [comment]
This is because your node_modules folder is too deep. Here is some general info about the issue you're encountering: http://stackoverflow.com/questions/26155135/node-npm-windows-file-paths-are-too-long-to-install-packages

I recommend you try to update to npm3, then do a clean reinstall.

**Comment by acostela** [comment]
Using npm3 and doing a clean reinstall will solve this problem :).

**Comment by aluxian** [comment]
@balakrishnan4587 I hope our tips has helped you fix this, please reopen if that's not the case.

**Comment by victoryforphil** [comment]
Im runing npm 3.10.3 and In having this issue!
