### ISSUE TITLE
Win installer.on, is not a function

### ISSUE THREAD

**Issue by Rubaloo** [Aluxian/electron-windows-installer#5]
Hi,

I get the next error since the last update (5 days ago). 

[14:08:35] **TypeError: winInstaller(...).on is not a function**
    at Gulp.<anonymous> (C:\Users\salvadru\Desktop\RootProject\container\gulpfile.js:36:6)
    at module.exports (C:\Users\salvadru\Desktop\RootProject\container\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\salvadru\Desktop\RootProject\container\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\salvadru\Desktop\RootProject\container\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\salvadru\Desktop\RootProject\container\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\salvadru\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

Thanks in advance.

**Comment by aluxian** [comment]
Can you show me your snippet of code that calls `winInstaller(...).on`?

**Comment by Rubaloo** [comment]
Yes,

gulp.task('create-installers', function (cb) {
    runSequence('create-frontend-installer',
                'create-backend-installer',
                cb);
});

gulp.task('create-frontend-installer', function(done) {
  winInstaller({
    appDirectory: './dist/frontend/3dpPU-win32-x64',
    outputDirectory: '../../installer/frontend',
    iconUrl: 'http://images.all-free-download.com/images/graphiclarge/abc.jpg',
    loadingGif:'../../installer/abc.gif',
    arch: 'ia32',
    exe:'abc.exe' 
  }).then(done).catch(done);
});

**Comment by Rubaloo** [comment]
Yes.

```
gulp.task('create-frontend-installer', function(done) {
  winInstaller({
    appDirectory: './dist/frontend/abc-win32-x64',
    outputDirectory: '../../installer/frontend',
    iconUrl: 'http://images.all-free-download.com/images/graphiclarge/abc.jpg',
    loadingGif:'../../installer/abc.gif',
    arch: 'ia32',
    exe:'abc.exe' 
  }).on('error', function(error){
    console.log(error);
    throw error;
  }).then(done).catch(done);
});
```

**Comment by aluxian** [comment]
`winInstaller({ ... })` returns a promise, not a stream. Therefore, you can't call `.on` on it. Here's how to fix your code:

```
gulp.task('create-frontend-installer', function(done) {
  winInstaller({
    appDirectory: './dist/frontend/abc-win32-x64',
    outputDirectory: '../../installer/frontend',
    iconUrl: 'http://images.all-free-download.com/images/graphiclarge/abc.jpg',
    loadingGif:'../../installer/abc.gif',
    arch: 'ia32',
    exe:'abc.exe' 
  })
  .then(function(){ done(); })
  .catch(done);
});
```

Also, note that using `.then(callback)` is not safe (in general) because `callback` would be called with the result of the promise as parameters, the first of which `callback` would think is an error. I made this change in the code above. Here's an example to understand what I mean:

```
var p = new Promise(function(resolve, reject) {
  // yada yada code
  if (somethingWorked)
    resolve(42); // in this case, the result of the promise would be one parameter: 42
  else
    reject(new Error('oops'));
});

function callback(err, result) {
  if (err)
    console.log('panic!');
  // else yada code
}

// now, if you do this:
p.then(callback);
// callback will be called with 42 as the error, which is not what you want
```
