### ISSUE TITLE
404 link in your main README.md

### ISSUE THREAD

**Issue by FranciscoG** [Aluxian/electron-windows-installer#7]
The "Squirrel Aware " links points to a 404 page: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/squirrel-events.md

![Squirrel Aware Screenshot](http://i.imgur.com/rmC7JR1.png)

**Comment by aluxian** [comment]
Fixed, thank you!

**Comment by FranciscoG** [comment]
that was so fast! thanks!
